import { homedir } from 'os';
import { join } from 'path';
import { existsSync, mkdirSync, writeFileSync, readFileSync, appendFileSync } from 'fs';

// ── Command tree for completion ──────────────────────────────────────────────
// This mirrors the command structure in ldc.js. Keep in sync when adding commands.
const COMMANDS = {
  login:             { desc: 'Authenticate with your Supabase project', opts: [] },
  whoami:            { desc: 'Show current login info', opts: [] },
  init:              { desc: 'Create a new project from the current directory', opts: ['--slug', '--dry-run'] },
  sync:              { desc: 'Re-scan directory and push new info', opts: ['--slug'] },
  link:              { desc: 'Link current directory to existing project', opts: [], args: ['slug'] },
  list:              { desc: 'List all projects', opts: [] },
  status:            { desc: 'Show summary of current project', opts: ['--slug'] },
  set:               { desc: 'Set a project field', opts: ['--slug'], args: ['field', 'value'] },
  export:            { desc: 'Export project data to JSON', opts: ['--slug', '--file'] },
  import:            { desc: 'Import project data from JSON', opts: ['--overwrite'], args: ['file'] },
  'agent-context':   { desc: 'Output agent context JSON', opts: ['--slug', '--no-snapshot'] },
  'context-versions':{ desc: 'List agent context version history', opts: ['--slug'] },
  'context-diff':    { desc: 'Diff two agent context versions', opts: ['--slug'], args: ['version1', 'version2'] },
  daemon:            { desc: 'Start the local HTTP bridge daemon', opts: ['--port'] },
  completions:       { desc: 'Generate or install shell completions', subs: {
    bash:  { desc: 'Output bash completion script' },
    zsh:   { desc: 'Output zsh completion script' },
    fish:  { desc: 'Output fish completion script' },
    install:{ desc: 'Auto-install completions for current shell', opts: ['--shell'] },
  }},
  add:               { desc: 'Add a resource to the project', subs: {
    command:    { desc: 'Add a command profile', opts: ['--slug', '--port', '--dir', '--health', '--confirm'] },
    port:       { desc: 'Add a port', opts: ['--slug', '--label', '--protocol', '--health'] },
    url:        { desc: 'Add a URL', opts: ['--slug', '--label', '--category', '--env'] },
    'env-key':  { desc: 'Add an expected env key', opts: ['--slug', '--classification', '--source', '--purpose', '--scope', '--optional'] },
    deployment: { desc: 'Add a deployment target', opts: ['--slug', '--url', '--branch', '--region', '--project-id', '--project-name'] },
  }},
  notes:             { desc: 'Manage project notes', subs: {
    list:   { desc: 'List all notes', opts: ['--slug', '--category'] },
    add:    { desc: 'Add a new note', opts: ['--slug', '--category', '--content', '--tags', '--pinned'] },
    remove: { desc: 'Remove a note by title', opts: ['--slug'] },
  }},
};

const TOP_COMMANDS = Object.keys(COMMANDS);

const SET_FIELDS = [
  'name', 'slug', 'description', 'repo-path', 'repo-url', 'package-manager',
  'default-branch', 'monorepo-paths', 'tags', 'status', 'notes',
  'danger-notes', 'hosting-platform',
];

const ADD_COMMAND_KINDS = ['dev', 'start', 'build', 'test', 'lint', 'migrate', 'seed', 'reset'];
const DEPLOYMENT_PLATFORMS = ['vercel', 'fly', 'render', 'railway'];
const DEPLOYMENT_ENVS = ['production', 'staging'];
const NOTE_CATEGORIES = ['general', 'gotcha', 'tip', 'bug', 'database', 'setup'];
const PORT_PROTOCOLS = ['http', 'https', 'tcp', 'ws'];

// ── Bash completion ──────────────────────────────────────────────────────────
export function generateBash() {
  return `# ldc bash completion — generated by "ldc completions bash"
# Add to ~/.bashrc: eval "$(ldc completions bash)"
_ldc_completions() {
  local cur prev words cword
  _init_completion -n = || return

  local commands="${TOP_COMMANDS.join(' ')}"
  local add_subs="command port url env-key deployment"
  local notes_subs="list add remove"
  local completions_subs="bash zsh fish install"

  # First argument: top-level command
  if [[ $cword -eq 1 ]]; then
    COMPREPLY=($(compgen -W "$commands --help --version" -- "$cur"))
    return
  fi

  local cmd="\${words[1]}"

  case "$cmd" in
    add)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "$add_subs" -- "$cur"))
        return
      fi
      local sub="\${words[2]}"
      case "$sub" in
        command)
          if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "--slug --port --dir --health --confirm" -- "$cur"))
          elif [[ $cword -eq 4 ]]; then
            COMPREPLY=($(compgen -W "${ADD_COMMAND_KINDS.join(' ')}" -- "$cur"))
          fi
          ;;
        port)
          [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "--slug --label --protocol --health" -- "$cur"))
          [[ "$prev" == "--protocol" ]] && COMPREPLY=($(compgen -W "${PORT_PROTOCOLS.join(' ')}" -- "$cur"))
          ;;
        url)
          [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "--slug --label --category --env" -- "$cur"))
          ;;
        env-key)
          [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "--slug --classification --source --purpose --scope --optional" -- "$cur"))
          ;;
        deployment)
          if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "--slug --url --branch --region --project-id --project-name" -- "$cur"))
          elif [[ $cword -eq 3 ]]; then
            COMPREPLY=($(compgen -W "${DEPLOYMENT_PLATFORMS.join(' ')}" -- "$cur"))
          elif [[ $cword -eq 4 ]]; then
            COMPREPLY=($(compgen -W "${DEPLOYMENT_ENVS.join(' ')}" -- "$cur"))
          fi
          ;;
      esac
      ;;
    notes)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "$notes_subs" -- "$cur"))
        return
      fi
      local sub="\${words[2]}"
      case "$sub" in
        list)
          [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "--slug --category" -- "$cur"))
          [[ "$prev" == "--category" ]] && COMPREPLY=($(compgen -W "${NOTE_CATEGORIES.join(' ')}" -- "$cur"))
          ;;
        add)
          [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "--slug --category --content --tags --pinned" -- "$cur"))
          [[ "$prev" == "--category" ]] && COMPREPLY=($(compgen -W "${NOTE_CATEGORIES.join(' ')}" -- "$cur"))
          ;;
        remove)
          [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "--slug" -- "$cur"))
          ;;
      esac
      ;;
    completions)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "$completions_subs" -- "$cur"))
        return
      fi
      local sub="\${words[2]}"
      [[ "$sub" == "install" && "$cur" == -* ]] && COMPREPLY=($(compgen -W "--shell" -- "$cur"))
      [[ "$sub" == "install" && "$prev" == "--shell" ]] && COMPREPLY=($(compgen -W "bash zsh fish" -- "$cur"))
      ;;
    set)
      if [[ $cword -eq 2 ]]; then
        COMPREPLY=($(compgen -W "${SET_FIELDS.join(' ')}" -- "$cur"))
      elif [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "--slug" -- "$cur"))
      fi
      ;;
    init)
      [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "--slug --dry-run" -- "$cur"))
      ;;
    sync|status|export|agent-context|context-versions)
      [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "--slug" -- "$cur"))
      ;;
    export)
      [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "--slug --file" -- "$cur"))
      [[ "$prev" == "--file" ]] && _filedir
      ;;
    import)
      if [[ $cword -eq 2 ]]; then
        _filedir json
      elif [[ "$cur" == -* ]]; then
        COMPREPLY=($(compgen -W "--overwrite" -- "$cur"))
      fi
      ;;
    context-diff)
      [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "--slug" -- "$cur"))
      ;;
    daemon)
      [[ "$cur" == -* ]] && COMPREPLY=($(compgen -W "--port" -- "$cur"))
      ;;
  esac
}

complete -F _ldc_completions ldc
`;
}

// ── Zsh completion ───────────────────────────────────────────────────────────
export function generateZsh() {
  return `#compdef ldc
# ldc zsh completion — generated by "ldc completions zsh"
# Add to ~/.zshrc: eval "$(ldc completions zsh)"
# Or save to a file in your $fpath: ldc completions zsh > ~/.zsh/completions/_ldc

_ldc() {
  local -a commands
  commands=(
${TOP_COMMANDS.map(cmd => `    '${cmd}:${COMMANDS[cmd].desc}'`).join('\n')}
  )

  _arguments -C \\
    '--help[Show help]' \\
    '--version[Show version]' \\
    '1:command:->cmd' \\
    '*::arg:->args'

  case $state in
    cmd)
      _describe 'ldc command' commands
      ;;
    args)
      case $words[1] in
        add)
          local -a add_subs
          add_subs=(
            'command:Add a command profile'
            'port:Add a port'
            'url:Add a URL'
            'env-key:Add an expected env key'
            'deployment:Add a deployment target'
          )
          _arguments -C '1:subcommand:->addsub' '*::arg:->addargs'
          case $state in
            addsub) _describe 'add subcommand' add_subs ;;
            addargs)
              case $words[1] in
                command)
                  _arguments \\
                    '--slug[Project slug]:slug' \\
                    '--port[Expected port]:port' \\
                    '--dir[Working directory]:dir:_directories' \\
                    '--health[Health check URL]:url' \\
                    '--confirm[Require confirmation]' \\
                    '1:name' \\
                    '2:kind:(${ADD_COMMAND_KINDS.join(' ')})' \\
                    '3:cmd'
                  ;;
                port)
                  _arguments \\
                    '--slug[Project slug]:slug' \\
                    '--label[Label]:label' \\
                    '--protocol[Protocol]:protocol:(${PORT_PROTOCOLS.join(' ')})' \\
                    '--health[Health check URL]:url' \\
                    '1:port'
                  ;;
                url)
                  _arguments \\
                    '--slug[Project slug]:slug' \\
                    '--label[Label]:label' \\
                    '--category[Category]:category' \\
                    '--env[Environment]:env' \\
                    '1:url'
                  ;;
                env-key)
                  _arguments \\
                    '--slug[Project slug]:slug' \\
                    '--classification[Classification]:class' \\
                    '--source[Source type]:source' \\
                    '--purpose[Purpose]:purpose' \\
                    '--scope[Env scope]:scope' \\
                    '--optional[Mark as optional]' \\
                    '1:key_name'
                  ;;
                deployment)
                  _arguments \\
                    '--slug[Project slug]:slug' \\
                    '--url[Production URL]:url' \\
                    '--branch[Git branch]:branch' \\
                    '--region[Region]:region' \\
                    '--project-id[Platform project ID]:id' \\
                    '--project-name[Platform project name]:name' \\
                    '1:platform:(${DEPLOYMENT_PLATFORMS.join(' ')})' \\
                    '2:environment:(${DEPLOYMENT_ENVS.join(' ')})'
                  ;;
              esac
              ;;
          esac
          ;;
        notes)
          local -a notes_subs
          notes_subs=(
            'list:List all notes'
            'add:Add a new note'
            'remove:Remove a note by title'
          )
          _arguments -C '1:subcommand:->notessub' '*::arg:->notesargs'
          case $state in
            notessub) _describe 'notes subcommand' notes_subs ;;
            notesargs)
              case $words[1] in
                list)
                  _arguments \\
                    '--slug[Project slug]:slug' \\
                    '--category[Filter by category]:category:(${NOTE_CATEGORIES.join(' ')})'
                  ;;
                add)
                  _arguments \\
                    '--slug[Project slug]:slug' \\
                    '--category[Category]:category:(${NOTE_CATEGORIES.join(' ')})' \\
                    '--content[Note content]:content' \\
                    '--tags[Comma-separated tags]:tags' \\
                    '--pinned[Pin this note]' \\
                    '1:title'
                  ;;
                remove)
                  _arguments \\
                    '--slug[Project slug]:slug' \\
                    '1:title'
                  ;;
              esac
              ;;
          esac
          ;;
        completions)
          local -a comp_subs
          comp_subs=(
            'bash:Output bash completion script'
            'zsh:Output zsh completion script'
            'fish:Output fish completion script'
            'install:Auto-install completions for current shell'
          )
          _arguments -C '1:subcommand:->compsub' '*::arg:->compargs'
          case $state in
            compsub) _describe 'completions subcommand' comp_subs ;;
            compargs)
              case $words[1] in
                install)
                  _arguments '--shell[Shell type]:shell:(bash zsh fish)'
                  ;;
              esac
              ;;
          esac
          ;;
        set)
          _arguments \\
            '--slug[Project slug]:slug' \\
            '1:field:(${SET_FIELDS.join(' ')})' \\
            '2:value'
          ;;
        init)
          _arguments \\
            '--slug[Override slug]:slug' \\
            '--dry-run[Show what would be created]'
          ;;
        sync|status|agent-context|context-versions)
          _arguments '--slug[Project slug]:slug'
          ;;
        export)
          _arguments \\
            '--slug[Project slug]:slug' \\
            '--file[Write to file]:file:_files'
          ;;
        import)
          _arguments \\
            '--overwrite[Overwrite existing records]' \\
            '1:file:_files -g "*.json"'
          ;;
        context-diff)
          _arguments \\
            '--slug[Project slug]:slug' \\
            '1:version1' \\
            '2:version2'
          ;;
        daemon)
          _arguments '--port[Port to listen on]:port'
          ;;
        link)
          _arguments '1:slug'
          ;;
      esac
      ;;
  esac
}

_ldc "$@"
`;
}

// ── Fish completion ──────────────────────────────────────────────────────────
export function generateFish() {
  const lines = [
    '# ldc fish completion — generated by "ldc completions fish"',
    '# Save to: ~/.config/fish/completions/ldc.fish',
    '',
    '# Disable file completion by default',
    'complete -c ldc -f',
    '',
    '# Helper: no subcommand entered yet',
    'function __ldc_no_subcommand',
    '  set -l tokens (commandline -opc)',
    '  test (count $tokens) -eq 1',
    'end',
    '',
    '# Helper: check current subcommand',
    'function __ldc_using_command',
    '  set -l tokens (commandline -opc)',
    '  set -l cmd $argv[1]',
    '  if test (count $tokens) -ge 2; and test $tokens[2] = $cmd',
    '    return 0',
    '  end',
    '  return 1',
    'end',
    '',
    '# Helper: check subcommand + sub-subcommand',
    'function __ldc_using_sub',
    '  set -l tokens (commandline -opc)',
    '  set -l cmd $argv[1]',
    '  set -l sub $argv[2]',
    '  if test (count $tokens) -ge 3; and test $tokens[2] = $cmd; and test $tokens[3] = $sub',
    '    return 0',
    '  end',
    '  return 1',
    'end',
    '',
    '# Top-level commands',
  ];

  for (const [name, cmd] of Object.entries(COMMANDS)) {
    lines.push(`complete -c ldc -n __ldc_no_subcommand -a ${name} -d '${cmd.desc}'`);
  }

  lines.push('');
  lines.push('# Global options');
  lines.push("complete -c ldc -n __ldc_no_subcommand -l help -d 'Show help'");
  lines.push("complete -c ldc -n __ldc_no_subcommand -l version -d 'Show version'");

  // Simple commands with --slug
  const slugOnlyCommands = ['sync', 'status', 'agent-context', 'context-versions', 'context-diff'];
  for (const cmd of slugOnlyCommands) {
    lines.push(`complete -c ldc -n '__ldc_using_command ${cmd}' -l slug -d 'Project slug' -r`);
  }

  // init
  lines.push('');
  lines.push('# init');
  lines.push("complete -c ldc -n '__ldc_using_command init' -l slug -d 'Override slug' -r");
  lines.push("complete -c ldc -n '__ldc_using_command init' -l dry-run -d 'Show without writing'");

  // set
  lines.push('');
  lines.push('# set');
  lines.push("complete -c ldc -n '__ldc_using_command set' -l slug -d 'Project slug' -r");
  for (const f of SET_FIELDS) {
    lines.push(`complete -c ldc -n '__ldc_using_command set' -a ${f} -d 'Set ${f}'`);
  }

  // export
  lines.push('');
  lines.push('# export');
  lines.push("complete -c ldc -n '__ldc_using_command export' -l slug -d 'Project slug' -r");
  lines.push("complete -c ldc -n '__ldc_using_command export' -l file -d 'Write to file' -r -F");

  // import
  lines.push('');
  lines.push('# import');
  lines.push("complete -c ldc -n '__ldc_using_command import' -l overwrite -d 'Overwrite existing records'");
  lines.push("complete -c ldc -n '__ldc_using_command import' -F");

  // daemon
  lines.push('');
  lines.push('# daemon');
  lines.push("complete -c ldc -n '__ldc_using_command daemon' -l port -d 'Port to listen on' -r");

  // add subcommands
  lines.push('');
  lines.push('# add');
  const addSubs = [
    ['command', 'Add a command profile'],
    ['port', 'Add a port'],
    ['url', 'Add a URL'],
    ['env-key', 'Add an expected env key'],
    ['deployment', 'Add a deployment target'],
  ];
  for (const [sub, desc] of addSubs) {
    lines.push(`complete -c ldc -n '__ldc_using_command add' -a ${sub} -d '${desc}'`);
  }

  // add command options
  lines.push("complete -c ldc -n '__ldc_using_sub add command' -l slug -d 'Project slug' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add command' -l port -d 'Expected port' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add command' -l dir -d 'Working directory' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add command' -l health -d 'Health check URL' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add command' -l confirm -d 'Require confirmation'");
  for (const k of ADD_COMMAND_KINDS) {
    lines.push(`complete -c ldc -n '__ldc_using_sub add command' -a ${k} -d '${k} command'`);
  }

  // add port options
  lines.push("complete -c ldc -n '__ldc_using_sub add port' -l slug -d 'Project slug' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add port' -l label -d 'Label' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add port' -l protocol -d 'Protocol' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add port' -l health -d 'Health check URL' -r");
  for (const p of PORT_PROTOCOLS) {
    lines.push(`complete -c ldc -n '__ldc_using_sub add port' -a ${p} -d '${p} protocol'`);
  }

  // add url options
  lines.push("complete -c ldc -n '__ldc_using_sub add url' -l slug -d 'Project slug' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add url' -l label -d 'Label' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add url' -l category -d 'Category' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add url' -l env -d 'Environment' -r");

  // add env-key options
  lines.push("complete -c ldc -n '__ldc_using_sub add env-key' -l slug -d 'Project slug' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add env-key' -l classification -d 'Classification' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add env-key' -l source -d 'Source type' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add env-key' -l purpose -d 'Purpose' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add env-key' -l scope -d 'Env scope' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add env-key' -l optional -d 'Mark as optional'");

  // add deployment options
  lines.push("complete -c ldc -n '__ldc_using_sub add deployment' -l slug -d 'Project slug' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add deployment' -l url -d 'Production URL' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add deployment' -l branch -d 'Git branch' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add deployment' -l region -d 'Region' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add deployment' -l project-id -d 'Platform project ID' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub add deployment' -l project-name -d 'Platform project name' -r");
  for (const p of DEPLOYMENT_PLATFORMS) {
    lines.push(`complete -c ldc -n '__ldc_using_sub add deployment' -a ${p} -d '${p}'`);
  }
  for (const e of DEPLOYMENT_ENVS) {
    lines.push(`complete -c ldc -n '__ldc_using_sub add deployment' -a ${e} -d '${e}'`);
  }

  // notes subcommands
  lines.push('');
  lines.push('# notes');
  const notesSubs = [
    ['list', 'List all notes'],
    ['add', 'Add a new note'],
    ['remove', 'Remove a note by title'],
  ];
  for (const [sub, desc] of notesSubs) {
    lines.push(`complete -c ldc -n '__ldc_using_command notes' -a ${sub} -d '${desc}'`);
  }

  lines.push("complete -c ldc -n '__ldc_using_sub notes list' -l slug -d 'Project slug' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub notes list' -l category -d 'Filter by category' -r");
  for (const cat of NOTE_CATEGORIES) {
    lines.push(`complete -c ldc -n '__ldc_using_sub notes list' -a ${cat} -d '${cat}'`);
  }

  lines.push("complete -c ldc -n '__ldc_using_sub notes add' -l slug -d 'Project slug' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub notes add' -l category -d 'Category' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub notes add' -l content -d 'Note content' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub notes add' -l tags -d 'Comma-separated tags' -r");
  lines.push("complete -c ldc -n '__ldc_using_sub notes add' -l pinned -d 'Pin this note'");
  for (const cat of NOTE_CATEGORIES) {
    lines.push(`complete -c ldc -n '__ldc_using_sub notes add' -a ${cat} -d '${cat}'`);
  }

  lines.push("complete -c ldc -n '__ldc_using_sub notes remove' -l slug -d 'Project slug' -r");

  // completions subcommands
  lines.push('');
  lines.push('# completions');
  const compSubs = [
    ['bash', 'Output bash completion script'],
    ['zsh', 'Output zsh completion script'],
    ['fish', 'Output fish completion script'],
    ['install', 'Auto-install completions for current shell'],
  ];
  for (const [sub, desc] of compSubs) {
    lines.push(`complete -c ldc -n '__ldc_using_command completions' -a ${sub} -d '${desc}'`);
  }
  lines.push("complete -c ldc -n '__ldc_using_sub completions install' -l shell -d 'Shell type' -r -a 'bash zsh fish'");

  lines.push('');
  return lines.join('\n');
}

// ── Install logic ────────────────────────────────────────────────────────────
export function detectShell() {
  const shell = process.env.SHELL || '';
  if (shell.includes('zsh')) return 'zsh';
  if (shell.includes('fish')) return 'fish';
  if (shell.includes('bash')) return 'bash';
  // On Windows, check MSYSTEM/MSYS for Git Bash
  if (process.env.MSYSTEM || process.env.MSYS) return 'bash';
  return null;
}

export function installCompletions(shell) {
  const home = homedir();
  let targetPath, script, rcFile, sourceLine;

  switch (shell) {
    case 'bash': {
      const dir = join(home, '.ldc');
      mkdirSync(dir, { recursive: true });
      targetPath = join(dir, 'completions.bash');
      script = generateBash();
      rcFile = join(home, '.bashrc');
      sourceLine = `\n# ldc CLI completions\n[ -f "${targetPath}" ] && source "${targetPath}"\n`;
      break;
    }
    case 'zsh': {
      const dir = join(home, '.ldc');
      mkdirSync(dir, { recursive: true });
      targetPath = join(dir, '_ldc');
      script = generateZsh();
      rcFile = join(home, '.zshrc');
      sourceLine = `\n# ldc CLI completions\nfpath=(${dir} $fpath)\nautoload -Uz compinit && compinit\n`;
      break;
    }
    case 'fish': {
      const dir = join(home, '.config', 'fish', 'completions');
      mkdirSync(dir, { recursive: true });
      targetPath = join(dir, 'ldc.fish');
      script = generateFish();
      // Fish auto-loads from completions dir, no rc edit needed
      rcFile = null;
      sourceLine = null;
      break;
    }
    default:
      return { success: false, error: `Unsupported shell: ${shell}` };
  }

  writeFileSync(targetPath, script);
  const result = { success: true, targetPath, shell };

  if (rcFile && sourceLine) {
    const rcContent = existsSync(rcFile) ? readFileSync(rcFile, 'utf8') : '';
    if (!rcContent.includes('ldc CLI completions')) {
      appendFileSync(rcFile, sourceLine);
      result.rcFile = rcFile;
      result.rcUpdated = true;
    } else {
      result.rcFile = rcFile;
      result.rcUpdated = false;
    }
  }

  return result;
}
